Models/ErrorViewModel.cs
namespace KamilaReveloExamenProgreso1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/KRmodelo1.cs
using System.ComponentModel.DataAnnotations;

namespace KamilaReveloExamenProgreso1.Models
{
    public class KRmodelo1
    {
        public int Id { get; set; }
        [Required]
        public string? Nombre { get; set; }
        public bool WithTea { get; set; }
        [Range(0.1, 99.99)]
        public decimal Precio { get; set; }
        [DataType(DataType.Date)]
        public DateTime FechaRegristo { get; set; }
        [DataType(DataType.Date)]
        public DateTime FechaFinal { get; set; }
    }
}

Controllers/HomeController.cs
using KamilaReveloExamenProgreso1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KamilaReveloExamenProgreso1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/KRmodelo1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KamilaReveloExamenProgreso1.Models;

namespace KamilaReveloExamenProgreso1.Controllers
{
    public class KRmodelo1Controller : Controller
    {
        private readonly KamilaReveloExamenProgreso1Context _context;

        public KRmodelo1Controller(KamilaReveloExamenProgreso1Context context)
        {
            _context = context;
        }

        // GET: KRmodelo1
        public async Task<IActionResult> KRIndex()
        {
            return View(await _context.KRmodelo1.ToListAsync());
        }

        // GET: KRmodelo1/Details/5
        public async Task<IActionResult> KRDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kRmodelo1 = await _context.KRmodelo1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kRmodelo1 == null)
            {
                return NotFound();
            }

            return View(kRmodelo1);
        }

        // GET: KRmodelo1/Create
        public IActionResult KRCreate()
        {
            return View();
        }

        // POST: KRmodelo1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> KRCreate([Bind("Id,Nombre,WithTea,Precio,FechaRegristo,FechaFinal")] KRmodelo1 kRmodelo1)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kRmodelo1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(KRIndex));
            }
            return View(kRmodelo1);
        }

        // GET: KRmodelo1/Edit/5
        public async Task<IActionResult> KREdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kRmodelo1 = await _context.KRmodelo1.FindAsync(id);
            if (kRmodelo1 == null)
            {
                return NotFound();
            }
            return View(kRmodelo1);
        }

        // POST: KRmodelo1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> KREdit(int id, [Bind("Id,Nombre,WithTea,Precio,FechaRegristo,FechaFinal")] KRmodelo1 kRmodelo1)
        {
            if (id != kRmodelo1.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kRmodelo1);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KRmodelo1Exists(kRmodelo1.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(KRIndex));
            }
            return View(kRmodelo1);
        }

        // GET: KRmodelo1/Delete/5
        public async Task<IActionResult> KRDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kRmodelo1 = await _context.KRmodelo1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kRmodelo1 == null)
            {
                return NotFound();
            }

            return View(kRmodelo1);
        }

        // POST: KRmodelo1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kRmodelo1 = await _context.KRmodelo1.FindAsync(id);
            if (kRmodelo1 != null)
            {
                _context.KRmodelo1.Remove(kRmodelo1);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(KRIndex));
        }

        private bool KRmodelo1Exists(int id)
        {
            return _context.KRmodelo1.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/KRmodelo1/Create.cshtml
@model KamilaReveloExamenProgreso1.Models.KRmodelo1

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>KRmodelo1</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="WithTea" /> @Html.DisplayNameFor(model => model.WithTea)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegristo" class="control-label"></label>
                <input asp-for="FechaRegristo" class="form-control" />
                <span asp-validation-for="FechaRegristo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFinal" class="control-label"></label>
                <input asp-for="FechaFinal" class="form-control" />
                <span asp-validation-for="FechaFinal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/KRmodelo1/Delete.cshtml
@model KamilaReveloExamenProgreso1.Models.KRmodelo1

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KRmodelo1</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WithTea)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WithTea)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegristo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegristo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFinal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaFinal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/KRmodelo1/Details.cshtml
@model KamilaReveloExamenProgreso1.Models.KRmodelo1

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>KRmodelo1</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WithTea)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WithTea)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegristo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegristo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFinal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaFinal)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/KRmodelo1/Edit.cshtml
@model KamilaReveloExamenProgreso1.Models.KRmodelo1

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>KRmodelo1</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="WithTea" /> @Html.DisplayNameFor(model => model.WithTea)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegristo" class="control-label"></label>
                <input asp-for="FechaRegristo" class="form-control" />
                <span asp-validation-for="FechaRegristo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFinal" class="control-label"></label>
                <input asp-for="FechaFinal" class="form-control" />
                <span asp-validation-for="FechaFinal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/KRmodelo1/KRCreate.cshtml
@model KamilaReveloExamenProgreso1.Models.KRmodelo1

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Nuevo Registro</h1>

<h4>KRmodelo1</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="KRCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="WithTea" /> @Html.DisplayNameFor(model => model.WithTea)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegristo" class="control-label"></label>
                <input asp-for="FechaRegristo" class="form-control" />
                <span asp-validation-for="FechaRegristo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFinal" class="control-label"></label>
                <input asp-for="FechaFinal" class="form-control" />
                <span asp-validation-for="FechaFinal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="KRIndex">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/KRmodelo1/KRDelete.cshtml
@model KamilaReveloExamenProgreso1.Models.KRmodelo1

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Registro</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KRmodelo1</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WithTea)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WithTea)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegristo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegristo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFinal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaFinal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="KRDelete" class="btn btn-danger" /> |
        <a asp-action="KRIndex">Back to List</a>
    </form>
</div>

Views/KRmodelo1/KRDetails.cshtml
@model KamilaReveloExamenProgreso1.Models.KRmodelo1

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles Registro</h1>

<div>
    <h4>KRmodelo1</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WithTea)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WithTea)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegristo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegristo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFinal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaFinal)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="KREdit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="KRIndex">Back to List</a>
</div>

Views/KRmodelo1/KREdit.cshtml
@model KamilaReveloExamenProgreso1.Models.KRmodelo1

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Registro</h1>

<h4>KRmodelo1</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="KREdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="WithTea" /> @Html.DisplayNameFor(model => model.WithTea)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegristo" class="control-label"></label>
                <input asp-for="FechaRegristo" class="form-control" />
                <span asp-validation-for="FechaRegristo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFinal" class="control-label"></label>
                <input asp-for="FechaFinal" class="form-control" />
                <span asp-validation-for="FechaFinal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="KRIndex">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/KRmodelo1/KRIndex.cshtml
@model IEnumerable<KamilaReveloExamenProgreso1.Models.KRmodelo1>

@{
    ViewData["Title"] = "Pagina Inical";
}

<h1>Pagina Inicial</h1>

<p>
    <a asp-action="KRCreate">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WithTea)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaRegristo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaFinal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WithTea)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaRegristo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaFinal)
            </td>
            <td>
                <a asp-action="KREdit" asp-route-id="@item.Id">KREdit</a> |
                <a asp-action="KRDetails" asp-route-id="@item.Id">KRDetails</a> |
                <a asp-action="KRDelete" asp-route-id="@item.Id">KRDelete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KamilaReveloExamenProgreso1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KamilaReveloExamenProgreso1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KamilaReveloExamen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="KRmodelo1" asp-action="KRIndex">KRmodelo1</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - KamilaReveloExamen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>